services:
  tipimate:
    image: ghcr.io/steveiliop56/tipimate:v2
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - TIPIMATE_NOTIFICATION_URL=some_shoutrrr_url
      - TIPIMATE_RUNTIPI_URL=https://localhost
      - TIPIMATE_JWT_SECRET=your_jwt_secret
      - TIPIMATE_DATABASE_PATH=/data/tipimate.db
      - TIPIMATE_INTERVAL=30
      - TIPIMATE_LOG_LEVEL=info
      - TIPIMATE_INSECURE=false
