services:
  tipimate:
    image: ghcr.io/steveiliop56/tipimate:v1
    container_name: tipimate
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - NOTIFY_URL=your-discord-token
      - RUNTIPI=runtipi-server-url
      - JWT_SECRET=your-jwt-secret
      - APPSTORE=https://github.com/runtipi/runtipi-appstore
      - DB_PATH=/data/tipimate.db
      - REFRESH=30
